# Generated by Django 4.0.2 on 2022-02-09 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(verbose_name='status code')),
                ('content', models.TextField(verbose_name='content')),
                ('created', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('view_token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='view token')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logresult_set', to='app.project')),
            ],
        ),
    ]
