# Generated by Django 4.0.2 on 2022-02-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_logresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='success_text',
            field=models.CharField(default='', max_length=256, verbose_name='success text'),
        ),
    ]
